INSERT INTO estados (estado, capital, sigla) VALUES
('Amazonas', 'Puerto Ayacucho', 'AM'),
('Anzoátegui', 'Barcelona', 'AN'),
('Apure', 'San Fernando de Apure', 'AP'),
('Aragua', 'Maracay', 'AR'),
('Barinas', 'Barinas', 'BA'),
('Bolívar', 'Ciudad Bolívar', 'BO'),
('Carabobo', 'Valencia', 'CA'),
('Cojedes', 'San Carlos', 'CO'),
('Delta Amacuro', 'Tucupita', 'DE'),
('Distrito Capital', 'Caracas', 'DC'),
('Falcón', 'Coro', 'FA'),
('Guárico', 'San Juan de los Morros', 'GU'),
('Lara', 'Barquisimeto', 'LA'),
('Mérida', 'Mérida', 'ME'),
('Miranda', 'Los Teques', 'MI'),
('Monagas', 'Maturín', 'MO'),
('Nueva Esparta', 'La Asunción', 'NE'),
('Portuguesa', 'Guanare', 'PO'),
('Sucre', 'Cumaná', 'SU'),
('Táchira', 'San Cristóbal', 'TA'),
('Trujillo', 'Trujillo', 'TR'),
('Vargas', 'La Guaira', 'VA'),
('Yaracuy', 'San Felipe', 'YA'),
('Zulia', 'Maracaibo', 'ZU');