# Generated by Django 5.0.6 on 2024-06-10 00:58

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('codEstado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('capital', models.CharField(max_length=30, verbose_name='Capital')),
                ('sigla', models.CharField(blank=True, max_length=2, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('cedper', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='cedula')),
                ('nomper', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre')),
                ('apeper', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Apellido')),
                ('telmovper', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None, verbose_name='Telf. Movil')),
                ('dependencia', models.CharField(choices=[('VPGI', 'VICEPRESIDENCIA GESTION INTERNA'), ('VPGC', 'VICEPRESIDENCIA DE GESTION COMERCIAL'), ('VPGC', 'VICEPRESIDENCIA DE GESTION COMERCIAL')], max_length=10, verbose_name='Ubicacion Admistración')),
                ('oficina', models.CharField(choices=[('ADM', 'GERENCIA DE ADMINISTRACION'), ('TEC', 'GERENCIA DE TECNOLOGIA')], max_length=10, verbose_name='Ubicacion Admistración')),
                ('municipio', models.CharField(max_length=30, verbose_name='Municipio')),
                ('Parroquia', models.CharField(max_length=30, verbose_name='Municipio')),
                ('centro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro de Votacion')),
                ('votacion', models.BooleanField(default=False, verbose_name='Votacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employes.estados', verbose_name='Estado')),
            ],
        ),
    ]
