# Generated by Django 5.0.6 on 2024-06-10 01:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employes',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.RemoveField(
            model_name='employes',
            name='Parroquia',
        ),
        migrations.AddField(
            model_name='employes',
            name='cargo',
            field=models.CharField(choices=[('ADM', 'GERENCIA DE ADMINISTRACION'), ('TEC', 'GERENCIA DE TECNOLOGIA')], default=datetime.datetime(2024, 6, 10, 1, 40, 22, 524635, tzinfo=datetime.timezone.utc), max_length=10, verbose_name='Oficina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employes',
            name='status',
            field=models.CharField(choices=[('AC', 'ACTIVO'), ('JUB', 'JUBILADO'), ('HP', 'HONORARO PROFESIONAL')], default=django.utils.timezone.now, max_length=3, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employes',
            name='oficina',
            field=models.CharField(choices=[('ADM', 'GERENCIA DE ADMINISTRACION'), ('TEC', 'GERENCIA DE TECNOLOGIA')], max_length=10, verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='employes',
            name='parroquia',
            field=models.CharField(default=1, max_length=30, verbose_name='Parroquia'),
            preserve_default=False,
        ),
    ]
