# Generated by Django 5.0.6 on 2024-06-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='centro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro de Votacion'),
        ),
    ]
