# Generated by Django 5.0.6 on 2024-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employes', '0002_alter_employes_options_remove_employes_parroquia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employes',
            options={'ordering': ['-cedper'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterField(
            model_name='employes',
            name='dependencia',
            field=models.CharField(choices=[('LIC', 'LICITACIÓN Y CONTRATACIÓN'), ('CON', 'CONSULTORIA JURIDICA'), ('AUD', 'AUDITORIA INTERNA'), ('VPGI', 'VICEPRESIDENCIA GESTION INTERNA'), ('VPGC', 'VICEPRESIDENCIA DE GESTION COMERCIAL'), ('VPGC', 'VICEPRESIDENCIA DE GESTION COMERCIAL'), ('PRE', 'PRESIDENCIA')], max_length=10, verbose_name='Ubicacion Admistración'),
        ),
        migrations.AlterField(
            model_name='employes',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'ACTIVO'), ('JUB', 'JUBILADO'), ('HP', 'HONORARO PROFESIONAL')], max_length=3, null=True, verbose_name='Status'),
        ),
        migrations.AlterModelTable(
            name='employes',
            table='employes',
        ),
        migrations.AlterModelTable(
            name='estados',
            table='estados',
        ),
    ]
