# Generated by Django 5.0.6 on 2024-06-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employes', '0003_alter_employes_options_alter_employes_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='cargo',
            field=models.CharField(choices=[('AS', 'ASISTENTE'), ('ESP', 'ESPECIALISTA'), ('GG', 'GERENTE GENERAL'), ('GL', 'GERENTE DE LINEA'), ('OB', 'OBRERO'), ('CH', 'CHOFER'), ('ND', 'NO DEFINIDO')], default='DN', max_length=10, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='employes',
            name='dependencia',
            field=models.CharField(choices=[('LIC', 'LICITACIÓN Y CONTRATACIÓN'), ('CON', 'CONSULTORIA JURIDICA'), ('AUD', 'AUDITORIA INTERNA'), ('VPGI', 'VICEPRESIDENCIA GESTION INTERNA'), ('VPGC', 'VICEPRESIDENCIA DE SERVICIOS HIDROLOGICOS'), ('VPGC', 'VICEPRESIDENCIA DE GESTION COMERCIAL'), ('PRE', 'PRESIDENCIA')], max_length=10, verbose_name='Ubicacion Admistración'),
        ),
        migrations.AlterField(
            model_name='employes',
            name='oficina',
            field=models.CharField(choices=[('GGD', 'GERENCIA DEL DESPACHO'), ('CEA', 'CENTRO DE ESTUDIOS DEL AGUA'), ('SEG', 'GERENCIA DE SEGUIMIENTO'), ('PRO', 'GERENCIA DE PROYECTOS'), ('TEC', 'GERENCIA DE TECNOLOGIA'), ('ADM', 'GERENCIA DE ADMINISTRACION'), ('PPO', 'GERENCIA DE PLANIFICACION PRESUPUESTO Y ORGANIZACION'), ('RRH', 'GERENCIA DE TALENTO HUMANO'), ('BPB', 'GERENCIA DE BIENES PUBLICOS'), ('COM', 'GERENCIA DE COMUNICACION'), ('GGSG', 'GERENCIA DE SEGURIDAD INTEGRAL SERVICIOS GENERALES'), ('FOR', 'GERENCIA DE FORTALECIMIENTO DEL PODER POPULAR'), ('GOP', 'GERENCIA DE OPERACIONES MANTENIMIENTO Y CALIDAD DEL AGUA'), ('GDC', 'GERENCIA DE DESARROLLO COMERCIAL'), ('GOC', 'GERENCIA DE OPERACIONES COMERCIALES'), ('N/A', 'NO APLICA')], max_length=10, verbose_name='Oficina'),
        ),
    ]
