Status = [
    ('AC', 'ACTIVO'),
    ('JUB', 'JUBILADO'),
    ('HP','HONORARIOS PROFESIONALES'),
]

Status_ordenadas = sorted(Status)
Dependencias = [
    ('LIC','LICITACIÓN Y CONTRATACIÓN'),
    ('CON','CONSULTORIA JURIDICA'),
    ('AUD','AUDITORIA INTERNA'),
    ('VPGI','VICEPRESIDENCIA GESTION INTERNA'),
    ('VPGC', 'VICEPRESIDENCIA DE SERVICIOS HIDROLOGICOS'),
    ('VPGC', 'VICEPRESIDENCIA DE GESTION COMERCIAL'),
    ('PRE', 'PRESIDENCIA'),   
]
Dependencias_ordenadas = sorted(Dependencias)

Oficinas = [
     
     ('GGD','GERENCIA DEL DESPACHO'),
     ('CEA','CENTRO DE ESTUDIOS DEL AGUA'),
     ('SEG','GERENCIA DE SEGUIMIENTO'),
     ('PRO','GERENCIA DE PROYECTOS'),
     ('TEC','GERENCIA DE TECNOLOGIA'),
     ('ADM','GERENCIA DE ADMINISTRACION'),
     ('PPO','GERENCIA DE PLANIFICACION PRESUPUESTO Y ORGANIZACION'),
     ('RRH','GERENCIA DE TALENTO HUMANO'),
     ('BPB','GERENCIA DE BIENES PUBLICOS'),
     ('COM','GERENCIA DE COMUNICACION'),
     ('GGSG','GERENCIA DE SEGURIDAD INTEGRAL SERVICIOS GENERALES'),
     ('FOR','GERENCIA DE FORTALECIMIENTO DEL PODER POPULAR'),
     ('GOP','GERENCIA DE OPERACIONES MANTENIMIENTO Y CALIDAD DEL AGUA'),
     ('GDC','GERENCIA DE DESARROLLO COMERCIAL'),
     ('GGC','GERENCIA DE COMERCIALIZACIÓN'),
     ('GOC','GERENCIA DE OPERACIONES COMERCIALES'),
     ('GST', 'GERENCIA DE SOPORTE TECNICO COMERCIAL'),
     ('GTA', 'GERENCIA DE TRAMITES ADUANEROS'),
     ('N/A', 'NO APLICA'),
]
Oficinas_ordenadas = sorted(Oficinas)

Cargos = [
    ('AN', 'ANALISTA'),
    ('AS', 'ASISTENTE'),
    ('CH', 'CHOFER'),
    ('ESP', 'ESPECIALISTA'),
    ('GG', 'GERENTE GENERAL'),
    ('GL', 'GERENTE DE LINEA'),
    ('JD', 'JEFE DE DIVISIÓN'),
    ('ND', 'NO DEFINIDO'),
    ('OB', 'OBRERO'),
    ('SEC', 'SECRETARIA'),
    ('SUP', 'SUPERVISOR'),
]
Cargos_ordenadas = sorted(Cargos)